spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pjt3?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abcd123!

  mail:
    host: smtp.gmail.com
    port: 587
    username: # fill out
    password: # fill out
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: create

elasticsearch:
  host: localhost:9200
  username: elastic
  password: Abcd123!

cloud:
  aws:
    s3:
      bucket: pjt3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: # fill out
      secretKey: # fill out